name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: configure AWS credentials
      used: aws-actions/configure-aws-credentials@v1
      with:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-north-1'   
        SOURCE_DIR: 'public'
    - name: Deploy static site to S3 bucket  
      run: aws sync . s3://tws-github-pramote.finecart --delete

