name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-letest
    steps:
    - name: checkout 
    - uses: actions/checkout@v1

    - name: configure AWS credentials
      uses: aws-action/configure-aws-credential@v1
      with:
        args: --acl public-read --promo-demo-buckets  --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'   
        SOURCE_DIR: 'public'  
        
    - name: Deploy static site to S3 bucket  
      run: aws s3 sync . s3://tws0github-action-promo-demo-buckets  --delete



